# Generated by Django 2.1.5 on 2019-04-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20190423_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='phasefourdate',
            field=models.CharField(max_length=100),
        ),
    ]
