# Generated by Django 2.1.5 on 2019-10-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20190423_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
